apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-server
spec:
  secretName: nats-server
  issuerRef:
    kind: ClusterIssuer
    name: nats-ca
  usages:
    - server auth
  dnsNames:
    - nats
    - nats.nats.svc
    - nats.nats.svc.cluster.local
  privateKey:
    algorithm: Ed25519
