clusterName: capi
talosVersion: v1.12.7
kubernetesVersion: v1.35.4
endpoint: https://capi.k8s.nevi.network:6443

allowSchedulingOnControlPlanes: true

cniConfig:
  name: none

clusterPodNets:
  - 10.32.0.0/20
  - fdbc:ba6a:38de:32::/80
clusterSvcNets:
  - 10.96.0.0/12
  - fdbc:ba6a:38de:6000::/108

controlPlane:
  machineSpec:
    secureboot: true
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
  patches:
    - |
      # cluster-api compat
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:reader
            allowedKubernetesNamespaces:
              - kube-system

patches:
  - |
    ---
    # primary interface alias
    apiVersion: v1alpha1
    kind: LinkAliasConfig
    name: net0
    selector:
      match: true
    ---
    # network config from dhcp
    apiVersion: v1alpha1
    kind: DHCPv4Config
    name: net0
    ---
    apiVersion: v1alpha1
    kind: DHCPv6Config
    name: net0
    ---
    # time config
    apiVersion: v1alpha1
    kind: TimeSyncConfig
    ptp:
      devices: [/dev/ptp0]
  - |
    # disk config
    ---
    apiVersion: v1alpha1
    kind: VolumeConfig
    name: STATE
    encryption:
      provider: luks2
      keys:
        - slot: 0
          tpm: {}
    ---
    apiVersion: v1alpha1
    kind: VolumeConfig
    name: EPHEMERAL
    encryption:
      provider: luks2
      keys:
        - slot: 0
          tpm: {}
          lockToState: true
  - |
    # disable features
    cluster:
      network:
        cni:
          name: none
      proxy:
        disabled: true
      coreDNS:
        disabled: true
      discovery:
        enabled: false
      controllerManager:
        extraArgs:
          node-cidr-mask-size-ipv4: 24
          node-cidr-mask-size-ipv6: 96
    machine:
      network:
        kubespan:
          enabled: false
      features:
        hostDNS:
          enabled: true
          forwardKubeDNSToHost: false
      kubelet:
        extraArgs:
          cloud-provider: external
          rotate-server-certificates: true

nodes:
  - hostname: capi.k8s.nevi.network
    ipAddress: capi.k8s.nevi.network
    controlPlane: true
    installDisk: /dev/vda
    ignoreHostname: true
