apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pushsecret-nats.yaml
  - pushsecret-openbao.yaml
  - rbac.yaml
  - secretstore-openbao.yaml
  - secretstore.yaml
  - serviceaccount.yaml
