apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gateway-certs-share
  namespace: gateway
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: gateway-certs-share
      kind: SecretStore
  selector:
    secret:
      name: gateway
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: nats-server
