- name: Install standalone kubelet
  hosts: kubelet
  roles:
    - role: kubelet
      tags: kubelet

- name: Generate etcd CA
  hosts: etcd_ca
  roles:
    - role: etcd_ca
      tags: etcd
- name: Install etcd
  hosts: etcd
  roles:
    - role: etcd
      tags: etcd

- name: Generate patroni CA
  hosts: patroni_ca
  roles:
    - role: patroni_ca
      tags: patroni
- name: Install patroni
  hosts: patroni
  vars_files:
    - secrets/patroni.yaml
  roles:
    - role: patroni
      tags: patroni

- name: Install patroni-haproxy
  hosts: patroni_haproxy
  roles:
    - role: patroni_haproxy
      tags: patroni_haproxy

- name: Install kea
  hosts: kea
  vars_files:
    - secrets/kea.yaml
  roles:
    - role: kea
      tags: kea

- name: Install pdns-recursor
  hosts: pdns
  vars_files:
    - secrets/pdns.yaml
  roles:
    - role: pdns
      tags: pdns

- name: Install chrony
  hosts: chrony
  roles:
    - role: chrony
      tags: chrony

- name: Install dhcrelay
  hosts: dhcrelay
  roles:
    - role: dhcrelay
      tags: dhcrelay

- name: Generate caddy CA
  hosts: caddy_ca
  roles:
    - role: caddy_ca
      tags: caddy
- name: Install caddy
  hosts: caddy
  roles:
    - role: caddy
      tags: caddy
