apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tpeap-proxy-cert
spec:
  secretName: tpeap-proxy-cert
  issuerRef:
    name: tpeap-proxy-ca
  privateKey:
    algorithm: Ed25519
  commonName: tpeap-client
  usages:
    - digital signature
    - client auth
