---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: c20
spec:
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: TalosControlPlane
    name: c20-cp
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: ProxmoxCluster
    name: c20-pve
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxCluster
metadata:
  name: c20-pve
spec:
  controlPlaneEndpoint:
    host: c20.k8s.nevi.network
    port: 6443
  dnsServers:
    - 10.64.20.4
    - 10.64.20.5
  ipv4Config:
    addresses: [10.64.30.101-10.64.30.199]
    prefix: 24
    gateway: 10.64.30.1
  ipv6Config:
    addresses: [fdbc:ba6a:38de:30::101-fdbc:ba6a:38de:30::199]
    prefix: 64
    gateway: fdbc:ba6a:38de:30::1
  credentialsRef:
    name: c20-pve-auth
