---
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: c20-cp-v4
spec:
  addresses: [10.64.30.21-10.64.30.24]
  prefix: 24
  gateway: 10.64.30.1
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: c20-cp-v6
spec:
  addresses: [fdbc:ba6a:38de:30::21-fdbc:ba6a:38de:30::24]
  prefix: 64
  gateway: fdbc:ba6a:38de:30::1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: c20-cp
spec:
  version: v1.35.2
  replicas: 3
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      strategicPatches:
        - |
          ---
          # primary interface alias
          apiVersion: v1alpha1
          kind: LinkAliasConfig
          name: net0
          selector:
            match: true
          ---
          # time config
          apiVersion: v1alpha1
          kind: TimeSyncConfig
          ptp:
            devices: [/dev/ptp0]
        - |
          # disk config
          ---
          apiVersion: v1alpha1
          kind: VolumeConfig
          name: STATE
          encryption:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
          ---
          apiVersion: v1alpha1
          kind: VolumeConfig
          name: EPHEMERAL
          encryption:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
                lockToState: true
        - |
          # cluster-api compat
          machine:
            kubelet:
              extraArgs:
                cloud-provider: external
                rotate-server-certificates: true
            features:
              kubernetesTalosAPIAccess:
                enabled: true
                allowedRoles:
                  - os:reader
                allowedKubernetesNamespaces:
                  - kube-system
        - |
          # disable features
          cluster:
            network:
              cni:
                name: none
              podSubnets:
                - 10.32.16.0/20
                - fdbc:ba6a:38de:32:1::/80
              serviceSubnets:
                - 10.96.0.0/12
                - fdbc:ba6a:38de:6000::/108
            proxy:
              disabled: true
            coreDNS:
              disabled: true
            discovery:
              enabled: false
            controllerManager:
              extraArgs:
                node-cidr-mask-size-ipv4: 24
                node-cidr-mask-size-ipv6: 96
          machine:
            features:
              hostDNS:
                enabled: true
                forwardKubeDNSToHost: false
              kubePrism:
                enabled: true
                port: 7445
      talosVersion: v1.12.6
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: c20-cp-1-12-6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: c20-cp-1-12-6
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
      memoryMiB: 4096
      disks:
        bootVolume:
          disk: virtio0
          sizeGb: 100
      network:
        default:
          bridge: vmbr0
          model: virtio
          vlan: 30
          ipv4PoolRef:
            apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: c20-cp-v4
          ipv6PoolRef:
            apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: c20-cp-v6
      sourceNode: pve01
      templateID: 298
      vmIDRange:
        start: 300
        end: 399
      metadataSettings:
        providerIDInjection: true
