---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: c20-disk
spec:
  clusterName: c20
  replicas: 3
  selector:
    matchLabels: null
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 100%
  template:
    spec:
      clusterName: c20
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: TalosConfigTemplate
          name: c20-disk-1
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ProxmoxMachineTemplate
        name: c20-disk-a
      version: v1.35.3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: c20-disk-1
spec:
  template:
    spec:
      generateType: worker
      strategicPatches:
        - |
          ---
          # primary interface alias
          apiVersion: v1alpha1
          kind: LinkAliasConfig
          name: net0
          selector:
            match: true
          ---
          # time config
          apiVersion: v1alpha1
          kind: TimeSyncConfig
          ptp:
            devices: [/dev/ptp0]
        - |
          # disk config
          ---
          apiVersion: v1alpha1
          kind: VolumeConfig
          name: STATE
          encryption:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
          ---
          apiVersion: v1alpha1
          kind: VolumeConfig
          name: EPHEMERAL
          encryption:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
                lockToState: true
        - |
          # zfs disk config
          ---
          apiVersion: v1alpha1
          kind: RawVolumeConfig
          name: openebs-disk
          provisioning:
            diskSelector:
              match: "!system_disk"
            minSize: 30GiB
          encryption:
            provider: luks2
            keys:
              - slot: 0
                tpm: {}
          ---
          machine:
            kernel:
              modules:
                - name: zfs
            nodeLabels:
              nevi.network/storage: zfs
        - |
          machine:
            kubelet:
              extraArgs:
                cloud-provider: external
                rotate-server-certificates: true
        - |
          machine:
            features:
              hostDNS:
                enabled: true
                forwardKubeDNSToHost: false
              kubePrism:
                enabled: true
                port: 7445
      talosVersion: v1.12.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxMachineTemplate
metadata:
  name: c20-disk-a
spec:
  template:
    spec:
      checks:
        skipCloudInitStatus: true
      numCores: 4
      memoryMiB: 8192
      disks:
        bootVolume:
          disk: virtio0
          sizeGb: 20
      network:
        networkDevices:
          - bridge: vmbr0
            model: virtio
            vlan: 30
      sourceNode: pve01
      templateID: 306
      vmIDRange:
        start: 300
        end: 399
      metadataSettings:
        providerIDInjection: true
