apiVersion: v1
kind: Service
metadata:
  name: httpbun
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app.kubernetes.io/name: httpbun
  ports:
    - name: http
      port: 80
      targetPort: http
