---
cluster:
  discovery:
    enabled: false
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: ens18
clientIdentifier: mac
---
apiVersion: v1alpha1
kind: DHCPv6Config
name: ens18
clientIdentifier: mac
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - /dev/ptp0
