global:
  seaweedfs:
    enableReplication: true
    replicationPlacement: "002"

master:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 256Mi
  extraEnvironmentVars:
    GOMEMLIMIT: 200MiB
  data:
    type: "persistentVolumeClaim"
    storageClass: openebs-zfs
    size: 10Gi
  logs:
    type: "emptyDir"

volume:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 1Gi
  extraEnvironmentVars:
    GOMEMLIMIT: 900MiB
  dataDirs:
    - name: data
      type: "persistentVolumeClaim"
      storageClass: openebs-zfs
      size: 10Gi
      maxVolumes: 0

filer:
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 256Mi
  extraEnvironmentVars:
    GOMEMLIMIT: 200MiB
  data:
    type: "persistentVolumeClaim"
    storageClass: openebs-zfs
    size: 10Gi
  logs:
    type: "emptyDir"

s3:
  replicas: 2
  enabled: true
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: s3
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 1Gi
  extraEnvironmentVars:
    GOMEMLIMIT: 900MiB
  logs:
    type: "emptyDir"

admin:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      memory: 128Mi
  extraEnvironmentVars:
    GOMEMLIMIT: 100MiB

worker:
  enabled: true
  extraEnvironmentVars:
    GOMEMLIMIT: 200MiB
