{{- range $name, $val := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  {{- with ($val).labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
