- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    system: true
- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    group: etcd
    home: '{{ etcd_data_dir }}'
    create_home: false
    shell: /usr/sbin/nologin
    system: true

- name: Generate etcd cert base directory
  ansible.builtin.file:
    path: '{{ etcd_cert_basedir }}'
    state: directory
    owner: etcd
    group: etcd
    mode: '0o700'

- name: Install cryptography dependencies
  ansible.builtin.apt:
    name: python3-cryptography
    state: present

- name: Generate client private key
  community.crypto.openssl_privatekey:
    path: '{{ etcd_cert_basedir }}/client.key'
    type: Ed25519
    owner: etcd
    group: etcd
- name: Generate client CSR
  community.crypto.openssl_csr:
    path: '{{ etcd_cert_basedir }}/client.csr'
    privatekey_path: '{{ etcd_cert_basedir }}/client.key'
    subject_alt_name:
      - DNS:{{ inventory_hostname }}
      - IP:{{ ip }}
      - IP:127.0.0.1
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
    owner: etcd
    group: etcd
    return_content: true
  register: etcd_client_csr
- name: Sign client CSR
  delegate_to: '{{ groups.etcd_ca[0] }}'
  community.crypto.x509_certificate:
    path: '{{ etcd_ca_basedir }}/certs/{{ inventory_hostname }}-client.crt'
    csr_content: '{{ etcd_client_csr.csr }}'
    provider: ownca
    ownca_path: '{{ etcd_ca_basedir }}/ca.crt'
    ownca_privatekey_path: '{{ etcd_ca_basedir }}/ca.key'
    return_content: true
  register: etcd_client_crt

- name: Read CA certificate
  delegate_to: '{{ groups.etcd_ca[0] }}'
  ansible.builtin.slurp:
    src: '{{ etcd_ca_basedir }}/ca.crt'
  register: etcd_client_ca_crt
- name: Copy CA certificate
  ansible.builtin.copy:
    dest: '{{ etcd_cert_basedir }}/ca.crt'
    content: '{{ etcd_client_ca_crt.content | b64decode }}'
    mode: '0o644'

- name: Copy client certificate
  ansible.builtin.copy:
    dest: '{{ etcd_cert_basedir }}/client.crt'
    content: '{{ etcd_client_crt.certificate }}'
    owner: etcd
    group: etcd
    mode: '0o644'
