namespaces:
  cloudflare-tunnel:
  tpeap:
  seaweedfs:
  loki:
  openebs:
    labels:
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/warn: privileged
      pod-security.kubernetes.io/audit: privileged

cilium-bgp:
  values:
    ipv4: 10.64.31.16/28
    ipv6: fdbc:ba6a:38de:31:1::/80

gateway:
  values:
    dnsNames:
      - "*.c20.k8s.nevi.network"

cloudflare-tunnel:
  enabled: true
cloudflare-tunnel-policy:
  enabled: true
cloudflare-gateway:
  enabled: true

tpeap-cert:
  enabled: true

zfs-init:
  enabled: true

openebs-zfs:
  enabled: true

seaweedfs:
  enabled: true
seaweedfs-pdb:
  enabled: true
seaweedfs-policy:
  enabled: true

loki:
  enabled: true
loki-routes:
  enabled: true
