namespaces: {}

cilium-bgp:
  values:
    ipv4: 10.64.31.0/28
    ipv6: fdbc:ba6a:38de:31::/80

talos-ccm-pdb:
  enabled: false

# included w/ capi
cert-manager:
  enabled: false

gateway:
  values:
    dnsNames:
      - "*.capi.k8s.nevi.network"
