namespaces:
  argocd:
  envoy-gateway-system:
  cert-manager:
  gateway:
  external-dns:
  monitoring:
    labels:
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/warn: privileged
      pod-security.kubernetes.io/audit: privileged
  metrics-server:

cilium:
  enabled: true
  version: 1.19.2

cilium-preflight:
  enabled: false
  version: 1.19.2

cilium-bgp:
  enabled: true

talos-cloud-controller-manager:
  enabled: true
  version: 0.5.4

talos-ccm-pdb:
  enabled: true

coredns:
  enabled: true
  version: 1.45.2

argocd:
  enabled: false
  version: 9.4.15
argocd-routes:
  enabled: false

argocd-bootstrap:
  enabled: true

envoy-gateway:
  enabled: true
  version: v1.7.1

cert-manager:
  enabled: true
  version: v1.20.0

external-dns:
  enabled: true
  version: 1.20.0
external-dns-cert:
  enabled: true

gateway:
  enabled: true

metrics-server:
  enabled: true
  version: 3.13.0

cluster-ca:
  enabled: true

opentelemetry-kube-stack:
  enabled: true
  version: 0.14.8

signoz:
  enabled: false
  version: "0.116.2"
signoz-route:
  enabled: false

cloudflare-tunnel:
  enabled: false
  version: 0.3.2
  imageTag: 2026.3.0
cloudflare-tunnel-policy:
  enabled: false
cloudflare-gateway:
  enabled: false

tpeap-cert:
  enabled: false

httpbun:
  enabled: false
