cilium:
  enabled: true
  version: 1.18.6

cilium-preflight:
  enabled: false
  version: 1.18.6

cilium-bgp:
  enabled: true

talos-cloud-controller-manager:
  enabled: true
  version: 0.5.4

talos-ccm-pdb:
  enabled: true

coredns:
  enabled: true
  version: 1.45.2
