namespaces:
  argocd:
  envoy-gateway-system:
  cert-manager:
  gateway:
  external-dns:
  monitoring:
  metrics-server:

cilium:
  enabled: true
  version: 1.19.1

cilium-preflight:
  enabled: false
  version: 1.19.1

cilium-bgp:
  enabled: true

talos-cloud-controller-manager:
  enabled: true
  version: 0.5.4

talos-ccm-pdb:
  enabled: true

coredns:
  enabled: true
  version: 1.45.2

argocd-bootstrap:
  enabled: true

envoy-gateway:
  enabled: true
  version: v1.7.1

cert-manager:
  enabled: true
  version: v1.20.0

external-dns:
  enabled: true
  version: 1.20.0
external-dns-cert:
  enabled: true

gateway:
  enabled: true

metrics-server:
  enabled: true
  version: 3.13.0

cluster-ca:
  enabled: true

cloudflare-tunnel:
  enabled: false
  version: 0.3.2 # app version separate
cloudflare-tunnel-policy:
  enabled: false
cloudflare-gateway:
  enabled: false
