apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: gateway
      name: gateway
  hostnames:
    {{- toYaml .Values.hostnames | nindent 4 }}
  rules:
    - matches:
        - method:
            type: Exact
            service: opentelemetry.proto.collector.trace.v1.TraceService
            method: Export
      backendRefs:
        - group: ""
          kind: Service
          name: tempo
          port: 4317
          weight: 1
