nameservers:
  - net01.inf.nevi.network
  - net02.inf.nevi.network

soa: nevivurn.nevi.network. 0 86400 7200 3600000 60
ttl: 60

forward-zones:
  nevi.network:
    hosts:
      # misc.
      'null':
        ipv4: 0.0.0.0
        ipv6: '::'
      # legacy
      alrakis.proxy:
        ipv4: 10.42.43.2
      giausar.proxy:
        ipv4: 10.42.43.3
      funi:
        ipv4: 192.168.2.1
      athebyne:
        ipv4: 192.168.2.10
      # routers
      rtr01.inf:
        ipv4: 10.64.20.2
        ipv6: fdbc:ba6a:38de:20::2
      rtr02.inf:
        ipv4: 10.64.20.3
        ipv6: fdbc:ba6a:38de:20::3
      # netboxes
      net01.inf:
        ipv4: 10.64.20.4
        ipv6: fdbc:ba6a:38de:20::4
      net02.inf:
        ipv4: 10.64.20.5
        ipv6: fdbc:ba6a:38de:20::5
      net03.inf:
        ipv4: 10.64.20.6
        ipv6: fdbc:ba6a:38de:20::6
      # pve
      pve01.inf:
        ipv4: 10.64.20.11
        ipv6: fdbc:ba6a:38de:20::11
      # per-zone DHCP relays
      relay01.home:
        ipv4: 10.64.10.4
        ipv6: fdbc:ba6a:38de:10::4
      relay02.home:
        ipv4: 10.64.10.5
        ipv6: fdbc:ba6a:38de:10::5
      relay01.guest:
        ipv4: 10.64.11.4
        ipv6: fdbc:ba6a:38de:11::4
      relay02.guest:
        ipv4: 10.64.11.5
        ipv6: fdbc:ba6a:38de:11::5
      relay01.k8s:
        ipv4: 10.64.30.4
        ipv6: fdbc:ba6a:38de:30::4
      relay02.k8s:
        ipv4: 10.64.30.5
        ipv6: fdbc:ba6a:38de:30::5

reverse-zones:
  ipv4:
    - 10.64.10.0/24
    - 10.64.11.0/24
    - 10.64.20.0/24
    - 10.64.30.0/24
  ipv6:
    - fdbc:ba6a:38de:10::/64
    - fdbc:ba6a:38de:11::/64
    - fdbc:ba6a:38de:20::/64
    - fdbc:ba6a:38de:30::/64
