- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    system: true
  register: etcd_group
- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    group: etcd
    home: '{{ etcd_data_dir }}'
    create_home: false
    shell: /usr/sbin/nologin
    system: true
  register: etcd_user

- name: Generate etcd data directory
  ansible.builtin.file:
    path: '{{ etcd_data_dir }}'
    state: directory
    owner: etcd
    group: etcd
    mode: '0o700'
- name: Generate etcd configuration directory
  ansible.builtin.file:
    path: '{{ etcd_config_dir }}'
    state: directory
    owner: etcd
    group: etcd
    mode: '0o755'

- name: Generate etcd certs
  ansible.builtin.import_role:
    name: pki_certs
  vars:
    pki_user: etcd
    pki_group: etcd
    pki_dir: '{{ etcd_config_dir }}/ssl'
    pki_cert_id: server
    pki_ekus:
      - clientAuth
      - serverAuth
    pki_ca_host: '{{ etcd_ca_host }}'
    pki_ca_basedir: '{{ etcd_ca_basedir }}'

- name: Copy etcd configuration
  ansible.builtin.template:
    src: templates/etcd-config.yaml.j2
    dest: '{{ etcd_config_dir }}/etcd.yaml'
    owner: etcd
    group: etcd
    mode: '0o644'
  register: etcd_config

- name: Copy etcd pod manifest
  ansible.builtin.template:
    src: templates/etcd-pod.yaml.j2
    dest: /etc/kubernetes/manifests/etcd.yaml
    owner: root
    group: root
    mode: '0o644'
