---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-nodes
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - athebyne.inf.nevi.network:9100
        - pve01.mgmt.nevi.network:9100
        - rtr01.k8s.nevi.network:9100
        - rtr02.k8s.nevi.network:9100
  metricsPath: /metrics
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-smartctl
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - athebyne.inf.nevi.network:9633
        - pve01.mgmt.nevi.network:9633
  metricsPath: /metrics
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-icmp
  namespace: monitoring
spec:
  dnsSDConfigs:
    - names:
        - gateway.k8s.nevi.network
        - rtr01.k8s.nevi.network
        - rtr02.k8s.nevi.network
        - alrakis.prx.nevi.network
        - giausar.prx.nevi.network
        - alrakis.priv.nevi.network
        - giausar.priv.nevi.network
      type: A
      port: 80
      refreshInterval: 30s
    - names:
        - gateway.k8s.nevi.network
        - rtr01.k8s.nevi.network
        - rtr02.k8s.nevi.network
        - alrakis.prx.nevi.network
        - giausar.prx.nevi.network
        - alrakis.priv.nevi.network
        - giausar.priv.nevi.network
      type: AAAA
      port: 80
      refreshInterval: 30s
  metricsPath: /probe
  params:
    module:
      - icmp
  relabelings:
    - action: replace
      sourceLabels: [__address__]
      regex: '(.+):\d+'
      replacement: '$1'
      targetLabel: __param_target
    - action: replace
      sourceLabels: [__param_target]
      regex: '\[(.+)\]'
      replacement: '$1'
      targetLabel: __param_target
    - action: replace
      sourceLabels: [__meta_dns_name]
      targetLabel: instance
    - action: replace
      sourceLabels: [__param_target]
      targetLabel: address
    - action: replace
      targetLabel: __address__
      replacement: prometheus-blackbox-exporter.monitoring.svc:9115
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-http
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - https://ping.nevi.ing
  metricsPath: /probe
  params:
    module:
      - http_2xx
  relabelings:
    - action: replace
      sourceLabels: [__address__]
      targetLabel: __param_target
    - action: replace
      sourceLabels: [__param_target]
      targetLabel: instance
    - action: replace
      targetLabel: __address__
      replacement: prometheus-blackbox-exporter.monitoring.svc:9115
