apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: seaweedfs-s3
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: seaweedfs-s3
  # disable the response compression filter, breaks signatures that contain accept-encoding: identity
  compressor: []
