apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-lldap.yaml
  - ciliumnetworkpolicy.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
