- name: Create tpeap group
  ansible.builtin.group:
    name: tpeap
    system: true
  register: tpeap_group
- name: Create tpeap user
  ansible.builtin.user:
    name: tpeap
    group: tpeap
    home: "{{ tpeap_data_dir }}"
    create_home: false
    shell: /usr/sbin/nologin
    system: true
  register: tpeap_user

- name: Generate tpeap data directory
  ansible.builtin.file:
    path: "{{ tpeap_data_dir }}"
    state: directory
    owner: tpeap
    group: tpeap
    mode: "0o755"

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present

- name: Block external access to tpeap port 8043
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8043"
    in_interface: "!lo"
    jump: REJECT
    state: present
  register: tpeap_iptables_8043

- name: Block external access to tpeap port 8088
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8088"
    in_interface: "!lo"
    jump: REJECT
    state: present
  register: tpeap_iptables_8088

- name: Save iptables rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
  when: tpeap_iptables_8043.changed or tpeap_iptables_8088.changed

- name: Copy tpeap pod manifest
  ansible.builtin.template:
    src: templates/tpeap-pod.yaml.j2
    dest: /etc/kubernetes/manifests/tpeap.yaml
    owner: root
    group: root
    mode: "0o644"
