global:
  thanosRules:
    enabled: false

bucket:
  bucketweb:
    enabled: true
    extraArgs:
      - --enable-auto-gomemlimit
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

query:
  replicaCount: 1
  extraArgs:
    - --enable-auto-gomemlimit
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

compactor:
  extraArgs:
    - --enable-auto-gomemlimit
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  persistence:
    storageClass: openebs-zfs

storegateway:
  replicaCount: 1
  extraArgs:
    - --enable-auto-gomemlimit
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  persistence:
    storageClass: openebs-zfs

receive:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi
  persistence:
    storageClass: openebs-zfs
  extraArgs:
    - --enable-auto-gomemlimit
    # ref: https://prometheus.io/docs/guides/opentelemetry/#promoting-resource-attributes
    - --receive.otlp-promote-resource-attributes=service.instance.id
    - --receive.otlp-promote-resource-attributes=service.name
    - --receive.otlp-promote-resource-attributes=service.namespace
    - --receive.otlp-promote-resource-attributes=service.version
    - --receive.otlp-promote-resource-attributes=cloud.availability_zone
    - --receive.otlp-promote-resource-attributes=cloud.region
    - --receive.otlp-promote-resource-attributes=container.name
    - --receive.otlp-promote-resource-attributes=deployment.environment
    - --receive.otlp-promote-resource-attributes=deployment.environment.name
    - --receive.otlp-promote-resource-attributes=k8s.cluster.name
    - --receive.otlp-promote-resource-attributes=k8s.container.name
    - --receive.otlp-promote-resource-attributes=k8s.cronjob.name
    - --receive.otlp-promote-resource-attributes=k8s.daemonset.name
    - --receive.otlp-promote-resource-attributes=k8s.deployment.name
    - --receive.otlp-promote-resource-attributes=k8s.job.name
    - --receive.otlp-promote-resource-attributes=k8s.namespace.name
    - --receive.otlp-promote-resource-attributes=k8s.pod.name
    - --receive.otlp-promote-resource-attributes=k8s.replicaset.name
    - --receive.otlp-promote-resource-attributes=k8s.statefulset.name
