apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cluster-db
  namespace: cluster-db
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: cluster-db
      cnpg.io/podRole: instance
  ingress:
    - fromEntities:
        - cluster
