apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate-server.yaml
  - certificate-replication.yaml
  - cluster.yaml
  - database-lldap.yaml
  - database-authelia.yaml
