apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: {{ .Release.Namespace }}
  name: gateway
spec:
  secretName: gateway
  issuerRef:
    kind: ClusterIssuer
    name: le-prod
  dnsNames:
    {{- toYaml .Values.dnsNames | nindent 4 }}
  privateKey:
    {{- /* le does not support ed25519, and envoy only supports P-256 */}}
    algorithm: ECDSA
    size: 256
