---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  namespace: {{ .Release.Namespace }}
  name: direct-ok
spec:
  directResponse:
    statusCode: 200
---
# This "empty response" route is load-bearing; it is processed by external-dns
# to create gateway.$cluster which is used as the canonical address for the
# gateway itself (eg. from cloudflare-tunnel).
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: direct-ok
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
  hostnames:
    - {{ index .Values.dnsNames 0 | replace "*" "gateway" | quote }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: direct-ok
