crds:
  installPrometheus: false

cleanupJob:
  enabled: false

collectors:
  daemon:
    scrape_configs_file: ""
    presets:
      logsCollection:
        includeCollectorLogs: false
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    config:
      exporters:
        debug: {}
        otlphttp/logs:
          endpoint: https://otlp.k8s.nevi.network/logs
      extensions:
        health_check: {}
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 80
          spike_limit_percentage: 20
        resource/cluster:
          attributes:
            - key: k8s.cluster.name
              value: unknown
              action: upsert
      service:
        extensions:
          - health_check
        pipelines:
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - debug
          metrics:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - debug
          logs:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - otlphttp/logs
