cleanupJob:
  enabled: false

collectors:
  daemon:
    scrape_configs_file: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    config:
      extensions:
        health_check: {}
      receivers:
        kubeletstats:
          collection_interval: 10s
      processors:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 80
          spike_limit_percentage: 20
        resource/cluster:
          attributes:
            - key: k8s.cluster.name
              value: unknown
              action: upsert
      exporters:
        otlphttp/logs:
          endpoint: https://otlp.k8s.nevi.network/logs
        otlphttp/metrics:
          endpoint: https://otlp.k8s.nevi.network/metrics
        otlp/traces:
          endpoint: otlp.k8s.nevi.network:443
      service:
        extensions:
          - health_check
        pipelines:
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - otlp/traces
          metrics:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - otlphttp/metrics
          logs:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - k8sattributes
              - resourcedetection/env
              - resource/hostname
              - resource/cluster
              - batch
            exporters:
              - otlphttp/logs
